"""Add publication drafts table

Revision ID: 1a16c97bc29e
Revises: 917f22740106
Create Date: 2025-08-27 07:15:47.289473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a16c97bc29e'
down_revision = '917f22740106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publication_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_drafts_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_drafts_email'))

    op.drop_table('publication_drafts')
    # ### end Alembic commands ###
