"""add docid_rrids table

Revision ID: 30fd2740d9c1
Revises: 4e67049fd9a2
Create Date: 2026-02-24 20:29:04.138733

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30fd2740d9c1'
down_revision = '4e67049fd9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docid_rrids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('rrid', sa.String(length=50), nullable=False),
    sa.Column('rrid_name', sa.String(length=500), nullable=True),
    sa.Column('rrid_description', sa.Text(), nullable=True),
    sa.Column('rrid_resource_type', sa.String(length=100), nullable=True),
    sa.Column('rrid_url', sa.String(length=500), nullable=True),
    sa.Column('resolved_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'rrid', name='uq_docid_rrids_entity_rrid')
    )
    with op.batch_alter_table('docid_rrids', schema=None) as batch_op:
        batch_op.create_index('ix_docid_rrids_entity_lookup', ['entity_type', 'entity_id'], unique=False)

    # Add CHECK constraint for entity_type validation at DB level
    op.execute("ALTER TABLE docid_rrids ADD CONSTRAINT ck_docid_rrids_entity_type CHECK (entity_type IN ('publication', 'organization'))")

    # Seed sample RRID records for development testing
    # These use real RRID values from SciCrunch
    docid_rrids_table = sa.table('docid_rrids',
        sa.column('entity_type', sa.String),
        sa.column('entity_id', sa.Integer),
        sa.column('rrid', sa.String),
        sa.column('rrid_name', sa.String),
        sa.column('rrid_resource_type', sa.String),
        sa.column('rrid_url', sa.String),
        sa.column('created_at', sa.DateTime),
    )
    op.bulk_insert(docid_rrids_table, [
        {
            'entity_type': 'publication',
            'entity_id': 1,
            'rrid': 'RRID:SCR_002285',
            'rrid_name': 'ImageJ',
            'rrid_resource_type': 'software',
            'rrid_url': 'https://imagej.net/',
            'created_at': datetime.utcnow(),
        },
        {
            'entity_type': 'publication',
            'entity_id': 1,
            'rrid': 'RRID:SCR_003070',
            'rrid_name': 'Fiji',
            'rrid_resource_type': 'software',
            'rrid_url': 'https://fiji.sc/',
            'created_at': datetime.utcnow(),
        },
        {
            'entity_type': 'organization',
            'entity_id': 1,
            'rrid': 'RRID:SCR_011211',
            'rrid_name': 'African Academy of Sciences',
            'rrid_resource_type': 'core facility',
            'rrid_url': 'https://www.aasciences.africa/',
            'created_at': datetime.utcnow(),
        },
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE docid_rrids DROP CONSTRAINT IF EXISTS ck_docid_rrids_entity_type")

    with op.batch_alter_table('docid_rrids', schema=None) as batch_op:
        batch_op.drop_index('ix_docid_rrids_entity_lookup')

    op.drop_table('docid_rrids')
    # ### end Alembic commands ###
