"""dspace_mapping: add unique on dspace_uuid and publication_id, index on metadata_hash

Revision ID: 378233472f8a
Revises: f87ea28b5f4e
Create Date: 2026-02-24 17:22:02.006656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378233472f8a'
down_revision = 'f87ea28b5f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dspace_mappings', schema=None) as batch_op:
        batch_op.drop_index('ix_dspace_mappings_dspace_uuid')
        batch_op.create_index(batch_op.f('ix_dspace_mappings_dspace_uuid'), ['dspace_uuid'], unique=True)
        batch_op.drop_index('ix_dspace_mappings_publication_id')
        batch_op.create_index(batch_op.f('ix_dspace_mappings_publication_id'), ['publication_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_dspace_mappings_dspace_metadata_hash'), ['dspace_metadata_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dspace_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dspace_mappings_dspace_metadata_hash'))
        batch_op.drop_index(batch_op.f('ix_dspace_mappings_publication_id'))
        batch_op.create_index('ix_dspace_mappings_publication_id', ['publication_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_dspace_mappings_dspace_uuid'))
        batch_op.create_index('ix_dspace_mappings_dspace_uuid', ['dspace_uuid'], unique=False)

    # ### end Alembic commands ###
