"""Add view and download tracking tables

Revision ID: 3d14ffa0cffb
Revises: 693913402c91
Create Date: 2025-11-05 14:40:23.872083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d14ffa0cffb'
down_revision = '693913402c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publication_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_views_publication_id'), ['publication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_views_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_views_viewed_at'), ['viewed_at'], unique=False)

    op.create_table('file_downloads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('publication_file_id', sa.Integer(), nullable=True),
    sa.Column('publication_document_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['publication_document_id'], ['publication_documents.id'], ),
    sa.ForeignKeyConstraint(['publication_file_id'], ['publications_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_downloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_downloads_downloaded_at'), ['downloaded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_downloads_publication_document_id'), ['publication_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_downloads_publication_file_id'), ['publication_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_downloads_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_downloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_downloads_user_id'))
        batch_op.drop_index(batch_op.f('ix_file_downloads_publication_file_id'))
        batch_op.drop_index(batch_op.f('ix_file_downloads_publication_document_id'))
        batch_op.drop_index(batch_op.f('ix_file_downloads_downloaded_at'))

    op.drop_table('file_downloads')
    with op.batch_alter_table('publication_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_views_viewed_at'))
        batch_op.drop_index(batch_op.f('ix_publication_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_publication_views_publication_id'))

    op.drop_table('publication_views')
    # ### end Alembic commands ###
