"""add account_types table and account_type_id to user_accounts

Revision ID: 4e67049fd9a2
Revises: 378233472f8a
Create Date: 2026-02-24 17:27:47.697966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e67049fd9a2'
down_revision = '378233472f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    account_types_table = op.create_table('account_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_type_name')
    )
    op.bulk_insert(account_types_table, [
        {'id': 1, 'account_type_name': 'Individual'},
        {'id': 2, 'account_type_name': 'Institutional'},
    ])
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_accounts_account_type_id'), ['account_type_id'], unique=False)
        batch_op.create_foreign_key(None, 'account_types', ['account_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_accounts_account_type_id'))
        batch_op.drop_column('account_type_id')

    op.drop_table('account_types')
    # ### end Alembic commands ###
