"""Add Figshare and OJS fields to Publications

Revision ID: 52479ff41b80
Revises: ffdb9c770830
Create Date: 2025-12-03 18:48:15.479206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52479ff41b80'
down_revision = 'ffdb9c770830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('figshare_article_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('figshare_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('ojs_submission_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ojs_url', sa.String(length=500), nullable=True))
        batch_op.drop_constraint('uq_publications_document_docid', type_='unique')
        batch_op.drop_index('ix_publications_document_docid')
        batch_op.create_index(batch_op.f('ix_publications_document_docid'), ['document_docid'], unique=True)
        batch_op.create_index(batch_op.f('ix_publications_figshare_article_id'), ['figshare_article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_ojs_submission_id'), ['ojs_submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_ojs_submission_id'))
        batch_op.drop_index(batch_op.f('ix_publications_figshare_article_id'))
        batch_op.drop_index(batch_op.f('ix_publications_document_docid'))
        batch_op.create_index('ix_publications_document_docid', ['document_docid'], unique=False)
        batch_op.create_unique_constraint('uq_publications_document_docid', ['document_docid'])
        batch_op.drop_column('ojs_url')
        batch_op.drop_column('ojs_submission_id')
        batch_op.drop_column('figshare_url')
        batch_op.drop_column('figshare_article_id')

    # ### end Alembic commands ###
