"""Add publication audit trail and updated fields

Revision ID: 693913402c91
Revises: 1a16c97bc29e
Create Date: 2025-08-27 11:42:06.582821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693913402c91'
down_revision = '1a16c97bc29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_audit_trail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publication_audit_trail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_audit_trail_publication_id'), ['publication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_audit_trail_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_audit_trail_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_publications_updated_by'), ['updated_by'], unique=False)
        batch_op.create_foreign_key(None, 'user_accounts', ['updated_by'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_publications_updated_by'))
        batch_op.drop_column('updated_by')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('publication_audit_trail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_audit_trail_user_id'))
        batch_op.drop_index(batch_op.f('ix_publication_audit_trail_timestamp'))
        batch_op.drop_index(batch_op.f('ix_publication_audit_trail_publication_id'))

    op.drop_table('publication_audit_trail')
    # ### end Alembic commands ###
