"""Add Local Contexts integration tables

Revision ID: 709369017e99
Revises: add_resource_type_to_drafts
Create Date: 2026-01-14 19:07:50.937624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709369017e99'
down_revision = 'add_resource_type_to_drafts'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_contexts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('community_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_authoritative', sa.Boolean(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_attempt', sa.DateTime(), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('local_contexts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_contexts_external_id'), ['external_id'], unique=True)

    op.create_table('local_context_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('local_context_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('local_context_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_context_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_local_context_audit_log_local_context_id'), ['local_context_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_local_context_audit_log_publication_id'), ['publication_id'], unique=False)

    op.create_table('publication_local_contexts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('local_context_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('attached_at', sa.DateTime(), nullable=True),
    sa.Column('attached_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attached_by'], ['user_accounts.user_id'], ),
    sa.ForeignKeyConstraint(['local_context_id'], ['local_contexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_id', 'local_context_id', name='uq_publication_local_context')
    )
    with op.batch_alter_table('publication_local_contexts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_local_contexts_local_context_id'), ['local_context_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_local_contexts_publication_id'), ['publication_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_local_contexts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_local_contexts_publication_id'))
        batch_op.drop_index(batch_op.f('ix_publication_local_contexts_local_context_id'))

    op.drop_table('publication_local_contexts')
    with op.batch_alter_table('local_context_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_context_audit_log_publication_id'))
        batch_op.drop_index(batch_op.f('ix_local_context_audit_log_local_context_id'))
        batch_op.drop_index(batch_op.f('ix_local_context_audit_log_created_at'))

    op.drop_table('local_context_audit_log')
    with op.batch_alter_table('local_contexts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_contexts_external_id'))

    op.drop_table('local_contexts')
    # ### end Alembic commands ###
