"""Add identifier_type column to PublicationCreators

Revision ID: 7faa322ba678
Revises: bc17561cdd7a
Create Date: 2025-08-08 15:43:27.825435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7faa322ba678'
down_revision = 'bc17561cdd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('identifier',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('publication_documents', schema=None) as batch_op:
        batch_op.alter_column('handle_identifier',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Handle identifier for CORDRA integration',
               existing_nullable=True)
        batch_op.alter_column('external_identifier',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='External identifier (e.g., DOI from DataCite or Crossref)',
               existing_nullable=True)
        batch_op.alter_column('external_identifier_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Type of external identifier (e.g., DOI)',
               existing_nullable=True)
        batch_op.drop_index('idx_publication_documents_external_identifier')
        batch_op.drop_index('idx_publication_documents_handle_identifier')

    with op.batch_alter_table('publications_files', schema=None) as batch_op:
        batch_op.alter_column('handle_identifier',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Handle identifier for CORDRA integration',
               existing_nullable=True)
        batch_op.alter_column('external_identifier',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='External identifier (e.g., DOI from DataCite or Crossref)',
               existing_nullable=True)
        batch_op.alter_column('external_identifier_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Type of external identifier (e.g., DOI)',
               existing_nullable=True)
        batch_op.drop_index('idx_publications_files_external_identifier')
        batch_op.drop_index('idx_publications_files_handle_identifier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications_files', schema=None) as batch_op:
        batch_op.create_index('idx_publications_files_handle_identifier', ['handle_identifier'], unique=False)
        batch_op.create_index('idx_publications_files_external_identifier', ['external_identifier'], unique=False)
        batch_op.alter_column('external_identifier_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type of external identifier (e.g., DOI)',
               existing_nullable=True)
        batch_op.alter_column('external_identifier',
               existing_type=sa.VARCHAR(length=100),
               comment='External identifier (e.g., DOI from DataCite or Crossref)',
               existing_nullable=True)
        batch_op.alter_column('handle_identifier',
               existing_type=sa.VARCHAR(length=100),
               comment='Handle identifier for CORDRA integration',
               existing_nullable=True)

    with op.batch_alter_table('publication_documents', schema=None) as batch_op:
        batch_op.create_index('idx_publication_documents_handle_identifier', ['handle_identifier'], unique=False)
        batch_op.create_index('idx_publication_documents_external_identifier', ['external_identifier'], unique=False)
        batch_op.alter_column('external_identifier_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type of external identifier (e.g., DOI)',
               existing_nullable=True)
        batch_op.alter_column('external_identifier',
               existing_type=sa.VARCHAR(length=100),
               comment='External identifier (e.g., DOI from DataCite or Crossref)',
               existing_nullable=True)
        batch_op.alter_column('handle_identifier',
               existing_type=sa.VARCHAR(length=100),
               comment='Handle identifier for CORDRA integration',
               existing_nullable=True)

    with op.batch_alter_table('publication_creators', schema=None) as batch_op:
        batch_op.alter_column('identifier',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('identifier_type')

    # ### end Alembic commands ###
