"""Add identifier and identifier_type to PublicationProjects

Revision ID: 917f22740106
Revises: 9d6930747dbb
Create Date: 2025-08-08 16:45:35.994664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917f22740106'
down_revision = '9d6930747dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('identifier_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_projects', schema=None) as batch_op:
        batch_op.drop_column('identifier_type')
        batch_op.drop_column('identifier')

    # ### end Alembic commands ###
