"""Add identifier and identifier_type to PublicationOrganization

Revision ID: 9d6930747dbb
Revises: df906eb48852
Create Date: 2025-08-08 16:32:13.030838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6930747dbb'
down_revision = 'df906eb48852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('identifier_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_organizations', schema=None) as batch_op:
        batch_op.drop_column('identifier_type')
        batch_op.drop_column('identifier')

    # ### end Alembic commands ###
