"""Add DSpace integration mapping table

Revision ID: a15d722168c8
Revises: 3d14ffa0cffb
Create Date: 2025-11-12 20:13:39.036288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15d722168c8'
down_revision = '3d14ffa0cffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dspace_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dspace_handle', sa.String(length=255), nullable=False),
    sa.Column('dspace_uuid', sa.String(length=36), nullable=False),
    sa.Column('dspace_url', sa.String(length=500), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('dspace_metadata_hash', sa.String(length=64), nullable=True),
    sa.Column('docid_metadata_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dspace_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dspace_mappings_dspace_handle'), ['dspace_handle'], unique=True)
        batch_op.create_index(batch_op.f('ix_dspace_mappings_dspace_uuid'), ['dspace_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_dspace_mappings_publication_id'), ['publication_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dspace_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dspace_mappings_publication_id'))
        batch_op.drop_index(batch_op.f('ix_dspace_mappings_dspace_uuid'))
        batch_op.drop_index(batch_op.f('ix_dspace_mappings_dspace_handle'))

    op.drop_table('dspace_mappings')
    # ### end Alembic commands ###
