"""Initial migration - all models

Revision ID: bc17561cdd7a
Revises: 
Create Date: 2025-06-12 11:11:42.240075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc17561cdd7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier_cstr', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_documents', schema=None) as batch_op:
        batch_op.drop_column('identifier_cstr')

    # ### end Alembic commands ###
