"""Add CORDRA sync tracking fields to Publications

Revision ID: c85e997ed2ef
Revises: 52479ff41b80
Create Date: 2025-12-08 17:28:25.827402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85e997ed2ef'
down_revision = '52479ff41b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cordra_synced', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cordra_synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_column('cordra_synced_at')
        batch_op.drop_column('cordra_synced')

    # ### end Alembic commands ###
