"""Add identifier and identifier_type to PublicationFunders

Revision ID: df906eb48852
Revises: 7faa322ba678
Create Date: 2025-08-08 15:56:31.762288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df906eb48852'
down_revision = '7faa322ba678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_funders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('identifier_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_funders', schema=None) as batch_op:
        batch_op.drop_column('identifier_type')
        batch_op.drop_column('identifier')

    # ### end Alembic commands ###
