"""figshare_docid_fix: doi nullable, document_docid nullable, figshare_article_id unique, add cordra_status columns

Revision ID: f87ea28b5f4e
Revises: 709369017e99
Create Date: 2026-02-24 17:02:16.643291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87ea28b5f4e'
down_revision = '709369017e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cordra_status', sa.String(length=20), nullable=False, server_default='PENDING'))
        batch_op.add_column(sa.Column('cordra_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cordra_object_id', sa.String(length=128), nullable=True))
        batch_op.alter_column('document_docid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('doi',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_index('ix_publications_figshare_article_id')
        batch_op.create_index(batch_op.f('ix_publications_figshare_article_id'), ['figshare_article_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_publications_cordra_object_id'), ['cordra_object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_cordra_status'), ['cordra_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_cordra_status'))
        batch_op.drop_index(batch_op.f('ix_publications_cordra_object_id'))
        batch_op.drop_index(batch_op.f('ix_publications_figshare_article_id'))
        batch_op.create_index('ix_publications_figshare_article_id', ['figshare_article_id'], unique=False)
        batch_op.alter_column('doi',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('document_docid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('cordra_object_id')
        batch_op.drop_column('cordra_error')
        batch_op.drop_column('cordra_status')

    # ### end Alembic commands ###
