"""Add handle_url column to publications table

Revision ID: ffdb9c770830
Revises: a15d722168c8
Create Date: 2025-11-20 19:08:05.013665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffdb9c770830'
down_revision = 'a15d722168c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handle_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_column('handle_url')

    # ### end Alembic commands ###
